In [25]:
import requests
from bs4 import BeautifulSoup
import os
import zipfile
import numpy as np
import pandas as pd

url = 'https://s3.amazonaws.com/tripdata/'

# load url content into soup
r = requests.get(url)
soup = BeautifulSoup(r.text, 'xml')   

# extract file names from soup
files = soup.find_all('Key')
clean_files = []
for i in range(len(files)-1):
    clean_files.append(files[i].get_text())

In [10]:
# download only the files that cannot directly be read in from AWS 
for file in clean_files[44:]:
    file_url = url + file
    #download files
    with open(file, "wb") as f:
            response = requests.get(file_url)
            f.write(response.content)
    # unzip data files
    with zipfile.ZipFile(file, "r") as zip_ref:
        zip_ref.extractall("tripdata")        
    # remove zipped file after unziping
    os.remove(file)

In [3]:
#load into DataFrames into dfs dictionary
#directory = 'tripdata/'
#dfs = {}

#for file in os.listdir(directory):
#    filename = os.fsdecode(file)
#    if filename.endswith('.csv'):
#        dfs[filename.split('.')[0]] = pd.read_csv(os.path.join(directory, filename))

In [30]:
len(clean_files)

142

In [1]:
#RANDOM SAMPLE TEST 
#random.seed(0)

import requests
from bs4 import BeautifulSoup
import os
import zipfile
import numpy as np
import pandas as pd

path = './tripdata/201907-citibike-tripdata.csv'

df_temp = pd.read_csv(path)
df_temp.columns = ['trip_duration','start_time','stop_time','start_station_id','start_station_name',\
                       'start_station_latitude','start_station_longitude','end_station_id',\
                       'end_station_name','end_station_latitude','end_station_longitude',\
                       'bike_id','user_type','birth_year','gender']

In [3]:
print(df_temp.shape) #2181064 rows 
df_temp.head()

(2181064, 15)

,trip_duration,start_time,stop_time,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bike_id,user_type,birth_year,gender
0,897,2019-07-01 00:00:00.1320,2019-07-01 00:14:58.0040,493.0,W 45 St & 6 Ave,40.756800,-73.982912,454.0,E 51 St & 1 Ave,40.754557,-73.965930,18340,Subscriber,1966,1
1,267,2019-07-01 00:00:05.1780,2019-07-01 00:04:32.4500,3143.0,5 Ave & E 78 St,40.776321,-73.964274,3226.0,W 82 St & Central Park West,40.782750,-73.971370,21458,Customer,1996,1
2,2201,2019-07-01 00:00:05.2130,2019-07-01 00:36:46.7490,317.0,E 6 St & Avenue B,40.724537,-73.981854,3469.0,India St & West St,40.731814,-73.959950,39874,Subscriber,1986,1
3,1660,2019-07-01 00:00:08.6010,2019-07-01 00:27:48.8050,249.0,Harrison St & Hudson St,40.718710,-74.009001,369.0,Washington Pl & 6 Ave,40.732241,-74.000264,38865,Subscriber,1988,1
4,109,2019-07-01 00:00:12.1580,2019-07-01 00:02:01.5670,3552.0,W 113 St & Broadway,40.805973,-73.964928,3538.0,W 110 St & Amsterdam Ave,40.802692,-73.962950,30256,Subscriber,1997,1

In [4]:
#DATA CLEANING

# remove trips that are longer than 1 hour 
df_temp = df_temp.loc[df_temp['trip_duration']<= 60*60]
    
#remove longitude and latitude outside of New York area 
df_temp = df_temp.loc[(df_temp['start_station_latitude']>40) & (df_temp['start_station_latitude']<41)] 
df_temp = df_temp.loc[(df_temp['end_station_longitude']>-74.5) & (df_temp['end_station_longitude']<-73.5)]

In [5]:
print(df_temp.shape) #2156227 rows

(2156227, 15)

In [35]:
#ADDING NEW VARIABLES 

#add age variables 
df_temp['age'] = 2020 - df_temp['birth_year'] 

#add revenue variable based on user_type 

#get unique bike count?

#remove those with long and lat outside of NYC area

In [7]:
df_temp_copy = df_temp

In [16]:
df_temp_copy['start_time'] = pd.to_datetime(df_temp_copy['start_time'])
df_temp_copy['stop_time'] = pd.to_datetime(df_temp_copy['stop_time'])

In [17]:
df_temp_copy['start_time'].dt.weekday

0          0
1          0
2          0
3          0
4          0
          ..
2181059    2
2181060    2
2181061    2
2181062    2
2181063    2
Name: start_time, Length: 2156227, dtype: int64

In [14]:
#start time variables 
df_temp_copy['year'] = df_temp_copy['start_time'].dt.year
df_temp_copy['month'] = df_temp_copy['start_time'].dt.day
df_temp_copy['year_month_day'] = df_temp_copy['start_time'].dt.day #
df_temp_copy['time_of_day'] = df_temp_copy['start_time'].dt.day
df_temp_copy['hour_of_day'] = df_temp_copy['start_time'].dt.hour #0 to 23 
df_temp_copy['week_day'] = df_temp_copy['start_time'].dt.weekday #0 to 23 

#stop time variables 
df1['stop_date'] = df1['stop_time'].dt.date
df1['stop_hour'] = df1['stop_time'].dt.hour

dtype('<M8[ns]')

In [24]:
df_temp_copy['week_day']

,trip_duration,start_time,stop_time,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bike_id,user_type,birth_year,gender
0,897,2019-07-01 00:00:00.132,2019-07-01 00:14:58.004,493.0,W 45 St & 6 Ave,40.756800,-73.982912,454.0,E 51 St & 1 Ave,40.754557,-73.965930,18340,Subscriber,1966,1
1,267,2019-07-01 00:00:05.178,2019-07-01 00:04:32.450,3143.0,5 Ave & E 78 St,40.776321,-73.964274,3226.0,W 82 St & Central Park West,40.782750,-73.971370,21458,Customer,1996,1
2,2201,2019-07-01 00:00:05.213,2019-07-01 00:36:46.749,317.0,E 6 St & Avenue B,40.724537,-73.981854,3469.0,India St & West St,40.731814,-73.959950,39874,Subscriber,1986,1
3,1660,2019-07-01 00:00:08.601,2019-07-01 00:27:48.805,249.0,Harrison St & Hudson St,40.718710,-74.009001,369.0,Washington Pl & 6 Ave,40.732241,-74.000264,38865,Subscriber,1988,1
4,109,2019-07-01 00:00:12.158,2019-07-01 00:02:01.567,3552.0,W 113 St & Broadway,40.805973,-73.964928,3538.0,W 110 St & Amsterdam Ave,40.802692,-73.962950,30256,Subscriber,1997,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2034737,810,2019-07-29 23:59:48.802,2019-07-30 00:13:19.469,3068.0,Humboldt St & Varet St,40.703172,-73.940636,3241.0,Monroe St & Tompkins Ave,40.686203,-73.944694,34363,Customer,1973,2
2034738,271,2019-07-29 23:59:52.724,2019-07-30 00:04:24.684,432.0,E 7 St & Avenue A,40.726218,-73.983799,311.0,Norfolk St & Broome St,40.717227,-73.988021,33981,Subscriber,1975,2
2034739,526,2019-07-29 23:59:54.993,2019-07-30 00:08:41.646,545.0,E 23 St & 1 Ave,40.736502,-73.978095,497.0,E 17 St & Broadway,40.737050,-73.990093,21160,Subscriber,1986,1
2034740,1281,2019-07-29 23:59:56.103,2019-07-30 00:21:17.336,473.0,Rivington St & Chrystie St,40.721101,-73.991925,401.0,Allen St & Rivington St,40.720196,-73.989978,27811,Subscriber,1948,2
2034741,2247,2019-07-29 23:59:56.754,2019-07-30 00:37:24.400,173.0,Broadway & W 49 St,40.760683,-73.984527,368.0,Carmine St & 6 Ave,40.730386,-74.002150,38678,Subscriber,1994,1

In [ ]:
# take a 5% subset of monthly file for analysis and another 5% of the remaining dataset as test dataset for ML
rows = len(df_temp)
size = int(rows/20)
random.seed(0)
selected_idx = random.sample(range(1,rows), size)
skip_idx = list(set(df_temp.index)-set(selected_idx))
test_idx = random.sample(skip_idx,int(len(skip_idx)/20))
df_train = df_temp.iloc[selected_idx,:].drop(['user_type','birth_year','gender'],axis=1)
df_test = df_temp.iloc[test_idx,:].drop(['user_type','birth_year','gender'],axis=1)

['201306-citibike-tripdata.zip',
 '201307-201402-citibike-tripdata.zip',
 '201307-citibike-tripdata.zip',
 '201308-citibike-tripdata.zip',
 '201309-citibike-tripdata.zip',
 '201310-citibike-tripdata.zip',
 '201311-citibike-tripdata.zip',
 '201312-citibike-tripdata.zip',
 '201401-citibike-tripdata.zip',
 '201402-citibike-tripdata.zip',
 '201403-citibike-tripdata.zip',
 '201404-citibike-tripdata.zip',
 '201405-citibike-tripdata.zip',
 '201406-citibike-tripdata.zip',
 '201407-citibike-tripdata.zip',
 '201408-citibike-tripdata.zip',
 '201409-citibike-tripdata.zip',
 '201410-citibike-tripdata.zip',
 '201411-citibike-tripdata.zip',
 '201412-citibike-tripdata.zip',
 '201501-citibike-tripdata.zip',
 '201502-citibike-tripdata.zip',
 '201503-citibike-tripdata.zip',
 '201504-citibike-tripdata.zip',
 '201505-citibike-tripdata.zip',
 '201506-citibike-tripdata.zip',
 '201507-citibike-tripdata.zip',
 '201508-citibike-tripdata.zip',
 '201509-citibike-tripdata.zip',
 '201510-citibike-tripdata.zip',
 '201511-citibike-tripdata.zip',
 '201512-citibike-tripdata.zip',
 '201601-citibike-tripdata.zip',
 '201602-citibike-tripdata.zip',
 '201603-citibike-tripdata.zip',
 '201604-citibike-tripdata.zip',
 '201605-citibike-tripdata.zip',
 '201606-citibike-tripdata.zip',
 '201607-citibike-tripdata.zip',
 '201608-citibike-tripdata.zip',
 '201609-citibike-tripdata.zip',
 '201610-citibike-tripdata.zip',
 '201611-citibike-tripdata.zip',
 '201612-citibike-tripdata.zip',
 '201701-citibike-tripdata.csv.zip',
 '201702-citibike-tripdata.csv.zip',
 '201703-citibike-tripdata.csv.zip',
 '201704-citibike-tripdata.csv.zip',
 '201705-citibike-tripdata.csv.zip',
 '201706-citibike-tripdata.csv.zip',
 '201707-citibike-tripdata.csv.zip',
 '201708-citibike-tripdata.csv.zip',
 '201709-citibike-tripdata.csv.zip',
 '201710-citibike-tripdata.csv.zip',
 '201711-citibike-tripdata.csv.zip',
 '201712-citibike-tripdata.csv.zip',
 '201801-citibike-tripdata.csv.zip',
 '201802-citibike-tripdata.csv.zip',
 '201803-citibike-tripdata.csv.zip',
 '201804-citibike-tripdata.csv.zip',
 '201805-citibike-tripdata.csv.zip',
 '201806-citibike-tripdata.csv.zip',
 '201807-citibike-tripdata.csv.zip',
 '201808-citibike-tripdata.csv.zip',
 '201809-citibike-tripdata.csv.zip',
 '201810-citibike-tripdata.csv.zip',
 '201811-citibike-tripdata.csv.zip',
 '201812-citibike-tripdata.csv.zip',
 '201901-citibike-tripdata.csv.zip',
 '201902-citibike-tripdata.csv.zip',
 '201903-citibike-tripdata.csv.zip',
 '201904-citibike-tripdata.csv.zip',
 '201905-citibike-tripdata.csv.zip',
 '201906-citibike-tripdata.csv.zip',
 '201907-citibike-tripdata.csv.zip',
 '201908-citibike-tripdata.csv.zip',
 '201909-citibike-tripdata.csv.zip',
 '201910-citibike-tripdata.csv.zip',
 '201911-citibike-tripdata.csv.zip',
 '201912-citibike-tripdata.csv.zip',
 '202001-citibike-tripdata.csv.zip',
 '202002-citibike-tripdata.csv.zip',
 '202003-citibike-tripdata.csv.zip',
 '202004-citibike-tripdata.csv.zip',
 '202005-citibike-tripdata.csv.zip',
 'JC-201509-citibike-tripdata.csv.zip',
 'JC-201510-citibike-tripdata.csv.zip',
 'JC-201511-citibike-tripdata.csv.zip',
 'JC-201512-citibike-tripdata.csv.zip',
 'JC-201601-citibike-tripdata.csv.zip',
 'JC-201602-citibike-tripdata.csv.zip',
 'JC-201603-citibike-tripdata.csv.zip',
 'JC-201604-citibike-tripdata.csv.zip',
 'JC-201605-citibike-tripdata.csv.zip',
 'JC-201606-citibike-tripdata.csv.zip',
 'JC-201607-citibike-tripdata.csv.zip',
 'JC-201608-citibike-tripdata.csv.zip',
 'JC-201609-citibike-tripdata.csv.zip',
 'JC-201610-citibike-tripdata.csv.zip',
 'JC-201611-citibike-tripdata.csv.zip',
 'JC-201612-citibike-tripdata.csv.zip',
 'JC-201701-citibike-tripdata.csv.zip',
 'JC-201702-citibike-tripdata.csv.zip',
 'JC-201703-citibike-tripdata.csv.zip',
 'JC-201704-citibike-tripdata.csv.zip',
 'JC-201705-citibike-tripdata.csv.zip',
 'JC-201706-citibike-tripdata.csv.zip',
 'JC-201707-citibike-tripdata.csv.zip',
 'JC-201708 citibike-tripdata.csv.zip',
 'JC-201709-citibike-tripdata.csv.zip',
 'JC-201710-citibike-tripdata.csv.zip',
 'JC-201711-citibike-tripdata.csv.zip',
 'JC-201712-citibike-tripdata.csv.zip',
 'JC-201801-citibike-tripdata.csv.zip',
 'JC-201802-citibike-tripdata.csv.zip',
 'JC-201803-citibike-tripdata.csv.zip',
 'JC-201804-citibike-tripdata.csv.zip',
 'JC-201805-citibike-tripdata.csv.zip',
 'JC-201806-citibike-tripdata.csv.zip',
 'JC-201807-citibike-tripdata.csv.zip',
 'JC-201808-citibike-tripdata.csv.zip',
 'JC-201809-citibike-tripdata.csv.zip',
 'JC-201810-citibike-tripdata.csv.zip',
 'JC-201811-citibike-tripdata.csv.zip',
 'JC-201812-citibike-tripdata.csv.zip',
 'JC-201901-citibike-tripdata.csv.zip',
 'JC-201902-citibike-tripdata.csv.zip',
 'JC-201903-citibike-tripdata.csv.zip',
 'JC-201904-citibike-tripdata.csv.zip',
 'JC-201905-citibike-tripdata.csv.zip',
 'JC-201906-citibike-tripdata.csv.zip',
 'JC-201907-citibike-tripdata.csv.zip',
 'JC-201908-citibike-tripdata.csv.zip',
 'JC-201909-citibike-tripdata.csv.zip',
 'JC-201910-citibike-tripdata.csv.zip',
 'JC-201911-citibike-tripdata.csv.zip',
 'JC-201912-citibike-tripdata.csv.zip',
 'JC-202001-citibike-tripdata.csv.zip',
 'JC-202002-citibike-tripdata.csv.zip',
 'JC-202003-citibike-tripdata.csv.zip',
 'JC-202004-citibike-tripdata.csv.zip',
 'JC-202005-citibike-tripdata.csv.zip']

In [19]:
####CLEAN DATA

In [40]:
def clean(dataframe):
    
    # remove trips that are longer than 1 hour 
    dataframe = dataframe.loc[dataframe['trip_duration']<= 60*60]
    
    #remove longitude and latitude outside of New York area 
    dataframe = dataframe.loc[(dataframe['start_station_latitude']>40) & (dataframe['start_station_latitude']<41)] 
    dataframe = dataframe.loc[(dataframe['end_station_longitude']>-74.5) & (dataframe['end_station_longitude']<-73.5)]
    
    #converting time to date time for pandas
    dataframe['start_time'] = pd.to_datetime(dataframe['start_time'])
    dataframe['stop_time'] = pd.to_datetime( dataframe['stop_time'])
    
    return dataframe

In [32]:
path = './tripdata/201907-citibike-tripdata.csv'

df_temp = pd.read_csv(path)
df_temp.columns = ['trip_duration','start_time','stop_time','start_station_id','start_station_name',\
                       'start_station_latitude','start_station_longitude','end_station_id',\
                       'end_station_name','end_station_latitude','end_station_longitude',\
                       'bike_id','user_type','birth_year','gender']

In [46]:
df_temp = clean(df_temp)

In [1]:
def newfeatures(data_frame):
    
    #add age variables 
    data_frame['age'] = np.subtract(2020, data_frame['birth_year']) 
    
    #start time variables 
    data_frame['year'] = data_frame['start_time'].dt.year
    
    #defining months
    data_frame['month'] = data_frame['start_time'].dt.month
    df_copy.loc[df_copy['month'] == 1, ['month']] = 'January'
    df_copy.loc[df_copy['month'] == 2, ['month']] = 'February'
    df_copy.loc[df_copy['month'] == 3, ['month']] = 'March'
    df_copy.loc[df_copy['month'] == 4, ['month']] = 'April'
    df_copy.loc[df_copy['month'] == 5, ['month']] = 'May'
    df_copy.loc[df_copy['month'] == 6, ['month']] = 'June'
    df_copy.loc[df_copy['month'] == 7, ['month']] = 'July'
    df_copy.loc[df_copy['month'] == 8, ['month']] = 'August'
    df_copy.loc[df_copy['month'] == 9, ['month']] = 'September'
    df_copy.loc[df_copy['month'] == 10, ['month']] = 'October'
    df_copy.loc[df_copy['month'] == 11, ['month']] = 'November'
    df_copy.loc[df_copy['month'] == 12, ['month']] = 'December'
    
    
    data_frame['start_date'] = data_frame['start_time'].dt.date
    data_frame['time_of_day'] = data_frame['start_time'].dt.time
    data_frame['hour_of_day'] = data_frame['start_time'].dt.hour #0 to 23 
    
    #defining days of the week and weekend 
    data_frame['week_day'] = data_frame['start_time'].dt.weekday #0 to 7 
    data_frame['weekend'] = [1 if 5<=x<=6 else 0 for x in data_frame['week_day']]
    df_copy.loc[df_copy['week_day'] == 0, ['week_day']] = 'Monday'
    df_copy.loc[df_copy['week_day'] == 1, ['week_day']] = 'Tuesday'
    df_copy.loc[df_copy['week_day'] == 2, ['week_day']] = 'Wednesday'
    df_copy.loc[df_copy['week_day'] == 3, ['week_day']] = 'Thursday'
    df_copy.loc[df_copy['week_day'] == 4, ['week_day']] = 'Friday'
    df_copy.loc[df_copy['week_day'] == 5, ['week_day']] = 'Saturday'
    df_copy.loc[df_copy['week_day'] == 6, ['week_day']] = 'Sunday'

    
    #stop time variables 
    data_frame['stop_date'] = data_frame['stop_time'].dt.date
    data_frame['stop_hour'] = data_frame['stop_time'].dt.hour
    data_frame['end_time_of_day'] = data_frame['stop_time'].dt.time

    return data_frame

In [2]:
df_copy=df_temp

NameError: name 'df_temp' is not defined

In [70]:
newfeatures(df_copy)

,trip_duration,start_time,stop_time,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,...,month,year_month_day,time_of_day,hour_of_day,week_day,weekend,stop_date,stop_hour,start_date,end_time_of_day
0,897,2019-07-01 00:00:00.132,2019-07-01 00:14:58.004,493.0,W 45 St & 6 Ave,40.756800,-73.982912,454.0,E 51 St & 1 Ave,40.754557,...,July,1,00:00:00.132000,0,Monday,0,2019-07-01,0,2019-07-01,00:14:58.004000
1,267,2019-07-01 00:00:05.178,2019-07-01 00:04:32.450,3143.0,5 Ave & E 78 St,40.776321,-73.964274,3226.0,W 82 St & Central Park West,40.782750,...,July,1,00:00:05.178000,0,Monday,0,2019-07-01,0,2019-07-01,00:04:32.450000
2,2201,2019-07-01 00:00:05.213,2019-07-01 00:36:46.749,317.0,E 6 St & Avenue B,40.724537,-73.981854,3469.0,India St & West St,40.731814,...,July,1,00:00:05.213000,0,Monday,0,2019-07-01,0,2019-07-01,00:36:46.749000
3,1660,2019-07-01 00:00:08.601,2019-07-01 00:27:48.805,249.0,Harrison St & Hudson St,40.718710,-74.009001,369.0,Washington Pl & 6 Ave,40.732241,...,July,1,00:00:08.601000,0,Monday,0,2019-07-01,0,2019-07-01,00:27:48.805000
4,109,2019-07-01 00:00:12.158,2019-07-01 00:02:01.567,3552.0,W 113 St & Broadway,40.805973,-73.964928,3538.0,W 110 St & Amsterdam Ave,40.802692,...,July,1,00:00:12.158000,0,Monday,0,2019-07-01,0,2019-07-01,00:02:01.567000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2181059,644,2019-07-31 23:59:45.295,2019-08-01 00:10:29.864,274.0,Lafayette Ave & Fort Greene Pl,40.686919,-73.976682,3409.0,Bergen St & Smith St,40.686744,...,July,31,23:59:45.295000,23,Wednesday,0,2019-08-01,0,2019-07-31,00:10:29.864000
2181060,589,2019-07-31 23:59:52.717,2019-08-01 00:09:42.087,3285.0,W 87 St & Amsterdam Ave,40.788390,-73.974700,3356.0,Amsterdam Ave & W 66 St,40.774667,...,July,31,23:59:52.717000,23,Wednesday,0,2019-08-01,0,2019-07-31,00:09:42.087000
2181061,1302,2019-07-31 23:59:52.828,2019-08-01 00:21:35.109,331.0,Pike St & Monroe St,40.711731,-73.991930,309.0,Murray St & West St,40.714979,...,July,31,23:59:52.828000,23,Wednesday,0,2019-08-01,0,2019-07-31,00:21:35.109000
2181062,353,2019-07-31 23:59:57.113,2019-08-01 00:05:50.135,3255.0,8 Ave & W 31 St,40.750585,-73.994685,482.0,W 15 St & 7 Ave,40.739355,...,July,31,23:59:57.113000,23,Wednesday,0,2019-08-01,0,2019-07-31,00:05:50.135000
2181063,274,2019-07-31 23:59:57.487,2019-08-01 00:04:32.207,3459.0,E 53 St & 3 Ave,40.757632,-73.969306,3134.0,3 Ave & E 62 St,40.763126,...,July,31,23:59:57.487000,23,Wednesday,0,2019-08-01,0,2019-07-31,00:04:32.207000

In [58]:
df_copy.loc[df_copy['week_day'] == 0, ['week_day']] = 'Monday'

,trip_duration,start_time,stop_time,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,...,year,month,year_month_day,time_of_day,hour_of_day,week_day,weekend,stop_date,stop_hour,start_date
0,897,2019-07-01 00:00:00.132,2019-07-01 00:14:58.004,493.0,W 45 St & 6 Ave,40.756800,-73.982912,454.0,E 51 St & 1 Ave,40.754557,...,2019,1,1,1,0,Monday,0,2019-07-01,0,2019-07-01
1,267,2019-07-01 00:00:05.178,2019-07-01 00:04:32.450,3143.0,5 Ave & E 78 St,40.776321,-73.964274,3226.0,W 82 St & Central Park West,40.782750,...,2019,1,1,1,0,Monday,0,2019-07-01,0,2019-07-01
2,2201,2019-07-01 00:00:05.213,2019-07-01 00:36:46.749,317.0,E 6 St & Avenue B,40.724537,-73.981854,3469.0,India St & West St,40.731814,...,2019,1,1,1,0,Monday,0,2019-07-01,0,2019-07-01
3,1660,2019-07-01 00:00:08.601,2019-07-01 00:27:48.805,249.0,Harrison St & Hudson St,40.718710,-74.009001,369.0,Washington Pl & 6 Ave,40.732241,...,2019,1,1,1,0,Monday,0,2019-07-01,0,2019-07-01
4,109,2019-07-01 00:00:12.158,2019-07-01 00:02:01.567,3552.0,W 113 St & Broadway,40.805973,-73.964928,3538.0,W 110 St & Amsterdam Ave,40.802692,...,2019,1,1,1,0,Monday,0,2019-07-01,0,2019-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2181059,644,2019-07-31 23:59:45.295,2019-08-01 00:10:29.864,274.0,Lafayette Ave & Fort Greene Pl,40.686919,-73.976682,3409.0,Bergen St & Smith St,40.686744,...,2019,31,31,31,23,2,0,2019-08-01,0,2019-07-31
2181060,589,2019-07-31 23:59:52.717,2019-08-01 00:09:42.087,3285.0,W 87 St & Amsterdam Ave,40.788390,-73.974700,3356.0,Amsterdam Ave & W 66 St,40.774667,...,2019,31,31,31,23,2,0,2019-08-01,0,2019-07-31
2181061,1302,2019-07-31 23:59:52.828,2019-08-01 00:21:35.109,331.0,Pike St & Monroe St,40.711731,-73.991930,309.0,Murray St & West St,40.714979,...,2019,31,31,31,23,2,0,2019-08-01,0,2019-07-31
2181062,353,2019-07-31 23:59:57.113,2019-08-01 00:05:50.135,3255.0,8 Ave & W 31 St,40.750585,-73.994685,482.0,W 15 St & 7 Ave,40.739355,...,2019,31,31,31,23,2,0,2019-08-01,0,2019-07-31
2181063,274,2019-07-31 23:59:57.487,2019-08-01 00:04:32.207,3459.0,E 53 St & 3 Ave,40.757632,-73.969306,3134.0,3 Ave & E 62 St,40.763126,...,2019,31,31,31,23,2,0,2019-08-01,0,2019-07-31