### This jupyter notebook shows the various methods available for downloading data:
- Locally
- Locally and Relatively
- Directly from AWS

In [13]:
# Import relevant libraries
import pandas as pd
from read_path_module import read_data_relative_path

In [11]:
# Reading data the standard way from within the current working directory
df_current_directory = pd.read_csv('JC-201909-citibike-tripdata.csv.zip').head(2)
df_current_directory

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,145,2019-09-01 00:00:37.6920,2019-09-01 00:03:03.0100,3640,Journal Square,40.73367,-74.062500,3206,Hilltop,40.731169,-74.057574,29303,Subscriber,1991,1
1,212,2019-09-01 00:03:00.6000,2019-09-01 00:06:33.3420,3194,McGinley Square,40.72534,-74.067622,3679,Bergen Ave,40.722104,-74.071455,29297,Subscriber,1993,2

In [12]:
# Reading data directly from aws using "Link Address"
df_aws = pd.read_csv('https://s3.amazonaws.com/tripdata/JC-201909-citibike-tripdata.csv.zip').head(2)
df_aws

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,145,2019-09-01 00:00:37.6920,2019-09-01 00:03:03.0100,3640,Journal Square,40.73367,-74.062500,3206,Hilltop,40.731169,-74.057574,29303,Subscriber,1991,1
1,212,2019-09-01 00:03:00.6000,2019-09-01 00:06:33.3420,3194,McGinley Square,40.72534,-74.067622,3679,Bergen Ave,40.722104,-74.071455,29297,Subscriber,1993,2

In [14]:
# Reading data using relative path up the directory
df_relative_upward = read_data_relative_path(
    relative_dataset_path = './data/citibike/JC-201909-citibike-tripdata.csv.zip',
    data_type='csv'
)

df_relative_upward.head(2)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,145,2019-09-01 00:00:37.6920,2019-09-01 00:03:03.0100,3640,Journal Square,40.73367,-74.062500,3206,Hilltop,40.731169,-74.057574,29303,Subscriber,1991,1
1,212,2019-09-01 00:03:00.6000,2019-09-01 00:06:33.3420,3194,McGinley Square,40.72534,-74.067622,3679,Bergen Ave,40.722104,-74.071455,29297,Subscriber,1993,2

In [18]:
# Importing a zip folder that includes multiple files within
import zipfile

zf = zipfile.ZipFile('201306-citibike-tripdata.zip') # having First.csv zipped file.
df = pd.read_csv(zf.open('201306-citibike-tripdata.csv'))

df.head(2)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,695,2013-06-01 00:00:01,2013-06-01 00:11:36,444,Broadway & W 24 St,40.742354,-73.989151,434.0,9 Ave & W 18 St,40.743174,-74.003664,19678,Subscriber,1983.0,1
1,693,2013-06-01 00:00:08,2013-06-01 00:11:41,444,Broadway & W 24 St,40.742354,-73.989151,434.0,9 Ave & W 18 St,40.743174,-74.003664,16649,Subscriber,1984.0,1

In [31]:
df = pd.read_csv('https://s3.amazonaws.com/tripdata/b') #.open('201306-citibike-tripdata.csv')

ValueError: Multiple files found in compressed zip file ['201306-citibike-tripdata.csv', '__MACOSX/', '__MACOSX/._201306-citibike-tripdata.csv']

### Failed Attempts at Downloading the non-csv titiled zipped files from aws

In [29]:
# import zipfile

# zf = zipfile.ZipFile('https://s3.amazonaws.com/tripdata/201306-citibike-tripdata.zip') # having First.csv zipped file.
# df = pd.read_csv(zf.open('201306-citibike-tripdata.csv'))

# df.head(2)

In [23]:
# pd.read_csv('https://s3.amazonaws.com/tripdata/201306-citibike-tripdata.zip'.open('201306-citibike-tripdata.csv'))

In [24]:
# # df = pd.read_csv('https://s3.amazonaws.com/tripdata/201306-citibike-tripdata.zip')

# from zipfile import ZipFile

# zip_file = ZipFile('https://s3.amazonaws.com/tripdata/201306-citibike-tripdata.zip')

# pd.read_csv(zip_file.open('201306-citibike-tripdata.csv'))

In [25]:
# import pandas as pd
# import boto3
# import io

# s3_file_key = '/201306-citibike-tripdata.zip'
# bucket = 'tripdata'

# s3 = boto3.client('s3')
# obj = s3.get_object(Bucket=bucket, Key=s3_file_key)

# initial_df = pd.read_csv(io.BytesIO(obj['Body'].read()))